### ISSUE TITLE
Upon starting script cmus continuously plays next song

### ISSUE THREAD

**Issue by APIUM** [mjc-506/cmus-album-shuffle#1]
Upon starting script cmus continuously plays next song, if in shuffle mode it will shuffle, etc. It's as if I'm holding down 'b'. I'm not a bash guy so I've not got much clue on a fix. Maybe I did something wrong though?

**Comment by mjc-506** [comment]
Good evening Apium,

Apologies for the late reply.

The script is fairly simple in concept - it remembers the album of the track currently playing, and if the album changes (ie, the end of the album is reached), it switches to shuffle mode (to get a new random album), turns off shuffle, and moves to the previous track until it finds the first track in the album.

This will fail if keybinding are changed, if you don't have any(many?) complete albums, or if I've made some bugs :-) I haven't updated cmus recently (I use this script on an embedded system on a carpc) but I will check what happens when I do. It is also not clever enough to sort itself out if the 'album' aaa/shuffle mode is set ('m') (it will never find the first track in the album, but will continue searching through that album). Does that match the behaviour you're experiencing?

**Comment by APIUM** [comment]
Finally got around to working it out, the issue was that I didn't have a ~/.cmus folder so the lastalbum couldn't be stored. Created a pull request with this change. 

Thanks for the script, works excellently now, and is exactly what I wanted. I wish it was in stock cmus.

**Comment by mjc-506** [comment]
Excellent, thanks for your contribution! I'm glad it's working for you now.
